course_name: "course_name"  # name of the folder where the outputs will be saved under /outputs
student_data_file_name: "student_data.xls"  # name of the file with student data, must be in /data
number_of_homeworks: 2  # number of homeworks so far
